# -*- coding: utf-8 -*-
"""
Ultimate Educational Edition: Shape & Symmetry-Aware Parametric Sweep Module (v37)
--------------------------------------------------------------------------------
This module performs automated parametric sensitivity sweeps on the generalized 
tunnel geometry generated by the preprocessor engine. It runs 3 distinct sweeps:
1. Rock Cohesion Sweep: Rock mass cohesion (c) vs. Crown Displacement & Plastic Zone Area %
2. Shotcrete Thickness Sweep: Shotcrete thickness (t_shot) vs. Crown Displacement & Lining Stress
3. Rockbolt Length Sweep: Rockbolt length (L_bolt) vs. Crown Displacement & Bolt Tension Force

All plots, legends, and outputs are fully in English, conforming to international 
academic publication and teaching standards.
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import splu
import os
import shutil
import json
import datetime

# =============================================================================
# 1. SMART PATH RESOLUTION & JSON PARAMETER LOADER
# =============================================================================
is_cloud = os.path.exists('/workspace') and os.name != 'nt'

if is_cloud:
    params_path = '/workspace/artifacts/parameters.json'
    os.makedirs('/workspace/artifacts', exist_ok=True)
else:
    script_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in globals() else os.getcwd()
    params_path = os.path.join(script_dir, 'parameters.json')

# Default parameters baseline
default_params = {
    "geometry": {
        "R_tunnel": 4.0,
        "H_wall": 3.0,
        "R_outer": 20.0,
        "H_depth": 100.0
    },
    "rock_mass": {
        "E_rock_init": 5000.0,
        "nu_rock": 0.25,
        "c_rock_init": 1.2,
        "phi_deg": 30.0,
        "gamma_rock": 0.025
    },
    "support_limits": {
        "E_shotcrete": 25000.0,
        "fc_shotcrete_limit": 16.7,
        "E_bolt": 210000.0,
        "d_bolt": 0.025,
        "T_bolt_limit": 200.0,
        "E_steel": 210000.0,
        "A_steel_per_m": 0.005,
        "I_steel_per_m": 4e-05,
        "fy_steel_limit": 235.0
    },
    "economic_rates": {
        "COST_SHOTCRETE_PER_M3": 250.0,
        "COST_ROCKBOLT_PER_M": 40.0,
        "COST_STEEL_BEAM_FLAT": 350.0
    },
    "active_simulation": {
        "use_shotcrete": True,
        "t_shot": 0.20,
        "use_rockbolts": True,
        "L_bolt_val": 3.0,
        "use_steel": True,
        "degradation_factor": 0.0
    },
    "batch_sweeps": {
        "cohesion_sweep": {
            "min_MPa": 0.2,
            "max_MPa": 2.0,
            "steps": 8
        },
        "shotcrete_sweep": {
            "min_cm": 0.0,
            "max_cm": 35.0,
            "steps": 8
        },
        "rockbolt_sweep": {
            "min_m": 0.0,
            "max_m": 6.0,
            "steps": 7
        }
    },
    "preprocessing": {
        "tunnel_type": "horseshoe", 
        "symmetry_type": "half",
        "R_invert": 8.0,
        "n_r": 16,
        "n_theta": 32,
        "stages": [
            {
                "stage_idx": 1,
                "name": "Heading Excavation (Kalota)",
                "excavate_above_y": 0.0,
                "active_supports": ["shotcrete", "rockbolts"]
            },
            {
                "stage_idx": 2,
                "name": "Bench Excavation (Stros)",
                "excavate_above_y": -99.0,
                "active_supports": ["shotcrete", "rockbolts", "steel_ribs"]
            }
        ]
    }
}

if not os.path.exists(params_path):
    with open(params_path, 'w', encoding='utf-8') as f_json:
        json.dump(default_params, f_json, indent=4, ensure_ascii=False)

try:
    with open(params_path, 'r', encoding='utf-8') as f_json:
        existing = json.load(f_json)
    updated = False
    if "preprocessing" not in existing:
        existing["preprocessing"] = default_params["preprocessing"]
        updated = True
    if "batch_sweeps" not in existing:
        existing["batch_sweeps"] = default_params["batch_sweeps"]
        updated = True
    if updated:
        with open(params_path, 'w', encoding='utf-8') as f_json:
            json.dump(existing, f_json, indent=4, ensure_ascii=False)
except Exception:
    pass

with open(params_path, 'r', encoding='utf-8') as f_json:
    params = json.load(f_json)

# Assign parameters
R_tunnel = params["geometry"]["R_tunnel"]
H_wall = params["geometry"]["H_wall"]
R_outer = params["geometry"]["R_outer"]
H_depth = params["geometry"]["H_depth"]

nu_rock = params["rock_mass"]["nu_rock"]
gamma_rock = params["rock_mass"]["gamma_rock"]

K0 = nu_rock / (1.0 - nu_rock)

E_shotcrete = params["support_limits"]["E_shotcrete"]
fc_shotcrete_limit = params["support_limits"]["fc_shotcrete_limit"]

E_bolt = params["support_limits"]["E_bolt"]
d_bolt = params["support_limits"]["d_bolt"]
A_bolt = np.pi * (d_bolt / 2)**2
T_bolt_limit = params["support_limits"]["T_bolt_limit"]

E_steel = params["support_limits"]["E_steel"]
A_steel_per_m = params["support_limits"]["A_steel_per_m"]
I_steel_per_m = params["support_limits"]["I_steel_per_m"]
fy_steel_limit = params["support_limits"]["fy_steel_limit"]

def get_D_e(E_val):
    Factor = E_val / ((1 + nu_rock) * (1 - 2 * nu_rock))
    return Factor * np.array([
        [1 - nu_rock,   nu_rock,     0],
        [nu_rock,     1 - nu_rock,   0],
        [0,             0,   (1 - 2 * nu_rock) / 2]
    ])

# =============================================================================
# 2. SHAPE-AWARE & SYMMETRY-AWARE PREPROCESSOR ENGINE
# =============================================================================
def get_R_boundary(theta, tunnel_type, R_tunnel, H_wall, R_invert=None):
    th_mapped = theta
    if th_mapped > np.pi/2:
        th_mapped = np.pi - th_mapped
    elif th_mapped < -np.pi/2:
        th_mapped = -np.pi - th_mapped
        
    if tunnel_type == "circular":
        return R_tunnel
    elif tunnel_type == "horseshoe":
        theta_corner = np.arctan2(-H_wall, R_tunnel)
        if th_mapped >= 0:
            return R_tunnel
        elif th_mapped >= theta_corner:
            return R_tunnel / np.cos(th_mapped)
        else:
            return -H_wall / np.sin(th_mapped)
    elif tunnel_type == "horseshoe_with_invert":
        theta_corner = np.arctan2(-H_wall, R_tunnel)
        if th_mapped >= 0:
            return R_tunnel
        elif th_mapped >= theta_corner:
            return R_tunnel / np.cos(th_mapped)
        else:
            if R_invert is None or R_invert <= R_tunnel:
                R_invert = R_tunnel * 2.0
            y_c = -H_wall + np.sqrt(R_invert**2 - R_tunnel**2)
            val = R_invert**2 - (y_c**2) * (np.cos(th_mapped)**2)
            if val < 0:
                return -H_wall / np.sin(th_mapped)
            return y_c * np.sin(th_mapped) + np.sqrt(val)
    else:
        return R_tunnel

def run_preprocessor(params):
    pre = params.get("preprocessing", default_params["preprocessing"])
    tunnel_type = pre.get("tunnel_type", "horseshoe")
    symmetry_type = pre.get("symmetry_type", "half")
    R_invert = pre.get("R_invert", 8.0)
    n_r = pre.get("n_r", 16)
    n_theta = pre.get("n_theta", 32)
    stages_config = pre.get("stages", default_params["preprocessing"]["stages"])
    
    if symmetry_type == "quarter":
        theta_vals = np.linspace(0, np.pi / 2, n_theta + 1)
    elif symmetry_type == "half":
        theta_vals = np.linspace(-np.pi / 2, np.pi / 2, n_theta + 1)
    else: # full
        theta_vals = np.linspace(-np.pi, np.pi, n_theta + 1)
        
    r_fac = np.linspace(0, 1, n_r + 1)**1.8
    
    nodes = []
    node_dict = {}
    node_idx = 0
    for i_r in range(n_r + 1):
        for j_th, th in enumerate(theta_vals):
            # Perfect loop topology matching for full 360 symmetry
            if symmetry_type == "full" and j_th == n_theta:
                node_dict[(i_r, j_th)] = node_dict[(i_r, 0)]
                continue
                
            R_boundary = get_R_boundary(th, tunnel_type, R_tunnel, H_wall, R_invert)
            r = R_boundary + (R_outer - R_boundary) * r_fac[i_r]
            x = r * np.cos(th)
            y = r * np.sin(th)
            nodes.append([x, y])
            node_dict[(i_r, j_th)] = node_idx
            node_idx += 1
            
    nodes = np.array(nodes)
    num_nodes = len(nodes)
    num_dofs = 2 * num_nodes
    
    elements = []
    for i in range(n_r):
        for j in range(n_theta):
            elements.append([
                node_dict[(i, j)],
                node_dict[(i + 1, j)],
                node_dict[(i + 1, j + 1)],
                node_dict[(i, j + 1)]
            ])
    elements = np.array(elements)
    num_elements = len(elements)
    
    fixed_dofs_base = []
    for i, (x, y) in enumerate(nodes):
        if symmetry_type in ["quarter", "half"]:
            if np.isclose(x, 0.0, atol=1e-3):
                fixed_dofs_base.append(2 * i)
        if symmetry_type == "quarter":
            if np.isclose(y, 0.0, atol=1e-3):
                fixed_dofs_base.append(2 * i + 1)
        r_node = np.sqrt(x**2 + y**2)
        if np.isclose(r_node, R_outer, atol=1e-2):
            fixed_dofs_base.extend([2 * i, 2 * i + 1])
    fixed_dofs_base = np.unique(fixed_dofs_base)
    
    element_stages = np.zeros(num_elements, dtype=int)
    last_stage_idx = stages_config[-1]["stage_idx"]
    element_stages[:] = last_stage_idx
    
    for stage in stages_config[:-1]:
        stg_id = stage["stage_idx"]
        exc_y = stage["excavate_above_y"]
        for idx, elem in enumerate(elements):
            if element_stages[idx] == last_stage_idx:
                elem_coords = nodes[elem]
                y_center = np.mean(elem_coords[:, 1])
                if y_center >= exc_y:
                    element_stages[idx] = stg_id
                    
    return {
        "nodes": nodes,
        "elements": elements,
        "node_dict": node_dict,
        "fixed_dofs_base": fixed_dofs_base,
        "element_stages": element_stages,
        "theta_vals": theta_vals,
        "stages_config": stages_config,
        "n_theta": n_theta,
        "r_fac": r_fac,
        "tunnel_type": tunnel_type,
        "symmetry_type": symmetry_type,
        "R_invert": R_invert
    }

# =============================================================================
# 3. ADVANCED PARAMETERIZED FEM SOLVER
# =============================================================================
def run_parameterized_simulation(
    E_rock_init_val,
    c_rock_init_val,
    phi_deg_val,
    use_shotcrete,
    t_shot,
    use_rockbolts,
    L_bolt_val,
    use_steel,
    degradation_factor=0.0
):
    prep = run_preprocessor(params)
    nodes = prep["nodes"]
    elements = prep["elements"]
    node_dict = prep["node_dict"]
    fixed_dofs_base = prep["fixed_dofs_base"]
    element_stages = prep["element_stages"]
    theta_vals = prep["theta_vals"]
    stages_config = prep["stages_config"]
    n_theta = prep["n_theta"]
    r_fac = prep["r_fac"]
    tunnel_type = prep["tunnel_type"]
    symmetry_type = prep["symmetry_type"]
    R_invert = prep["R_invert"]
    
    num_nodes = len(nodes)
    num_elements = len(elements)
    num_dofs = 2 * num_nodes
    
    E_rock = E_rock_init_val * (1.0 - 0.4 * degradation_factor)
    c_rock = c_rock_init_val * (1.0 - degradation_factor)
    phi = np.radians(phi_deg_val)
    sin_phi = np.sin(phi)
    cos_phi = np.cos(phi)
    D_e = get_D_e(E_rock)
    
    K_rock = np.zeros((num_dofs, num_dofs))
    gauss_pts = [-1 / np.sqrt(3), 1 / np.sqrt(3)]
    
    def shape_funcs(xi, eta):
        return 0.25 * np.array([
            [(1-xi)*(1-eta), (1+xi)*(1-eta), (1+xi)*(1+eta), (1-xi)*(1+eta)]
        ]), 0.25 * np.array([
            [-(1-eta),  (1-eta), (1+eta), -(1+eta)],
            [-(1-xi),  -(1+xi),  (1+xi),   (1-xi)]
        ])
        
    for elem in elements:
        elem_coords = nodes[elem]
        Ke = np.zeros((8, 8))
        for xi in gauss_pts:
            for eta in gauss_pts:
                _, dN_dxi = shape_funcs(xi, eta)
                J = dN_dxi @ elem_coords
                detJ = np.linalg.det(J)
                invJ = np.linalg.inv(J)
                dN_dx = invJ @ dN_dxi
                
                B = np.zeros((3, 8))
                for idx in range(4):
                    B[0, 2*idx] = dN_dx[0, idx]
                    B[1, 2*idx+1] = dN_dx[1, idx]
                    B[2, 2*idx] = dN_dx[1, idx]
                    B[2, 2*idx+1] = dN_dx[0, idx]
                Ke += B.T @ D_e @ B * detJ
                
        for i_local in range(4):
            for j_local in range(4):
                g_i = elem[i_local]
                g_j = elem[j_local]
                K_rock[2*g_i : 2*g_i+2, 2*g_j : 2*g_j+2] += Ke[2*i_local : 2*i_local+2, 2*j_local : 2*j_local+2]
                
    F_ext_stages = {stage["stage_idx"]: np.zeros(num_dofs) for stage in stages_config}
    for j in range(n_theta):
        n1 = node_dict[(0, j)]
        n2 = node_dict[(0, j+1)]
        p1, p2 = nodes[n1], nodes[n2]
        
        dx = p2[0] - p1[0]
        dy = p2[1] - p1[1]
        
        y_mid = 0.5 * (p1[1] + p2[1])
        sig_v = gamma_rock * (H_depth - y_mid)
        sig_h = K0 * sig_v
        
        fx = sig_h * dy
        fy = -sig_v * dx
        
        stage_idx_segment = element_stages[j]
        F_ext_stages[stage_idx_segment][2 * n1]     += 0.5 * fx
        F_ext_stages[stage_idx_segment][2 * n1 + 1] += 0.5 * fy
        F_ext_stages[stage_idx_segment][2 * n2]     += 0.5 * fx
        F_ext_stages[stage_idx_segment][2 * n2 + 1] += 0.5 * fy
        
    u_current = np.zeros(num_dofs)
    u_stage_results = {}
    yielded_stage_results = {}
    elem_stresses_stage_results = {}
    
    yielded_unsupported = np.zeros(num_elements, dtype=bool)
    elem_stresses_unsupported = np.zeros((num_elements, 3))
    
    u_install_state = None
    K_support_active = np.zeros((num_dofs, num_dofs))
    all_rockbolt_elements = []
    
    # Track rockbolts per stage
    rockbolt_elements_stage1 = []
    rockbolt_elements_stage2 = []
    
    for idx_stg, stage in enumerate(stages_config):
        stg_idx = stage["stage_idx"]
        act_supp = stage["active_supports"]
        
        segments_new = [j for j in range(n_theta) if element_stages[j] == stg_idx]
        
        EA_comp = 0.0
        if "shotcrete" in act_supp and use_shotcrete:
            EA_comp += E_shotcrete * t_shot
        if "steel_ribs" in act_supp and use_steel:
            EA_comp += E_steel * A_steel_per_m
            
        if EA_comp > 0:
            for j in segments_new:
                n1 = node_dict[(0, j)]
                n2 = node_dict[(0, j+1)]
                p1, p2 = nodes[n1], nodes[n2]
                L_seg = np.linalg.norm(p2 - p1)
                dx, dy = (p2[0] - p1[0]) / L_seg, (p2[1] - p1[1]) / L_seg
                k_liner = (EA_comp / L_seg) * np.array([
                    [ dx*dx,  dx*dy, -dx*dx, -dx*dy],
                    [ dx*dy,  dy*dy, -dx*dy, -dy*dy],
                    [-dx*dx, -dx*dy,  dx*dx,  dx*dy],
                    [-dx*dy, -dy*dy,  dx*dy,  dy*dy]
                ])
                dofs = [2*n1, 2*n1+1, 2*n2, 2*n2+1]
                for i_loc, d_i in enumerate(dofs):
                    for j_loc, d_j in enumerate(dofs):
                        K_support_active[d_i, d_j] += k_liner[i_loc, j_loc]
                        
        if "rockbolts" in act_supp and use_rockbolts and L_bolt_val > 0 and len(segments_new) > 0:
            nodes_new = sorted(list(set([j for j in range(n_theta+1) if (j < n_theta and j in segments_new) or (j > 0 and (j-1) in segments_new)])))
            num_bolts_this_stage = max(3, len(nodes_new) // 3)
            idx_selections = np.linspace(0, len(nodes_new) - 1, num_bolts_this_stage, dtype=int)
            bolt_theta_indices = [nodes_new[i] for i in idx_selections]
            
            for th_idx in bolt_theta_indices:
                cidar_node = node_dict[(0, th_idx)]
                th = theta_vals[th_idx]
                R_boundary = get_R_boundary(th, tunnel_type, R_tunnel, H_wall, R_invert=R_invert)
                radial_distances = r_fac * (R_outer - R_boundary)
                r_layer_idx = np.argmin(np.abs(radial_distances - L_bolt_val))
                ic_node = node_dict[(r_layer_idx, th_idx)]
                if stg_idx == 1:
                    rockbolt_elements_stage1.append([cidar_node, ic_node])
                else:
                    rockbolt_elements_stage2.append([cidar_node, ic_node])
                all_rockbolt_elements.append([cidar_node, ic_node])
                
                p1, p2 = nodes[cidar_node], nodes[ic_node]
                L = np.linalg.norm(p2 - p1)
                dx, dy = (p2[0] - p1[0]) / L, (p2[1] - p1[1]) / L
                k_truss = (E_bolt * A_bolt / L) * np.array([
                    [ dx*dx,  dx*dy, -dx*dx, -dx*dy],
                    [ dx*dy,  dy*dy, -dx*dy, -dy*dy],
                    [-dx*dx, -dx*dy,  dx*dx,  dx*dy],
                    [-dx*dy, -dy*dy,  dx*dy,  dy*dy]
                ])
                dofs = [2*cidar_node, 2*cidar_node+1, 2*ic_node, 2*ic_node+1]
                for i_loc, d_i in enumerate(dofs):
                    for j_loc, d_j in enumerate(dofs):
                        K_support_active[d_i, d_j] += k_truss[i_loc, j_loc]
                        
        locked_dofs = []
        for j in range(n_theta + 1):
            is_future = False
            if j < n_theta and element_stages[j] > stg_idx:
                is_future = True
            if j > 0 and element_stages[j-1] > stg_idx:
                is_future = True
            if is_future:
                # Lock nodes
                t_node = node_dict[(0, j)]
                locked_dofs.extend([2 * t_node, 2 * t_node + 1])
                
        fixed_dofs_current = np.unique(np.concatenate((fixed_dofs_base, locked_dofs)))
        active_dofs_current = np.setdiff1d(np.arange(num_dofs), fixed_dofs_current)
        
        F_accumulated = sum(F_ext_stages[stages_config[s]["stage_idx"]] for s in range(idx_stg + 1))
        
        if idx_stg == 0:
            lambda_natm = 0.40
            LU_rock = splu(csc_matrix(K_rock[np.ix_(active_dofs_current, active_dofs_current)]))
            for step in range(1, 5):
                F_current = (step / 10) * lambda_natm * F_ext_stages[stg_idx]
                u_current[active_dofs_current] = LU_rock.solve(F_current[active_dofs_current])
                
            u_install_state = u_current.copy()
            
            if len(stages_config) == 1:
                for idx_e, elem in enumerate(elements):
                    elem_coords = nodes[elem]
                    y_elem = np.mean(elem_coords[:, 1])
                    u_elem = u_install_state[np.array([2*elem[0], 2*elem[0]+1, 2*elem[1], 2*elem[1]+1,
                                                2*elem[2], 2*elem[2]+1, 2*elem[3], 2*elem[3]+1])]
                    
                    _, dN_dxi = shape_funcs(0.0, 0.0)
                    J = dN_dxi @ elem_coords
                    invJ = np.linalg.inv(J)
                    dN_dx = invJ @ dN_dxi
                    
                    B = np.zeros((3, 8))
                    for k in range(4):
                        B[0, 2*k] = dN_dx[0, k]
                        B[1, 2*k+1] = dN_dx[1, k]
                        B[2, 2*k] = dN_dx[1, k]
                        B[2, 2*k+1] = dN_dx[0, k]
                        
                    strain = B @ u_elem
                    elastic_stress = D_e @ strain
                    
                    sig_v_elem = gamma_rock * (H_depth - y_elem)
                    sig_h_elem = K0 * sig_v_elem
                    excavation_stress = np.array([-sig_h_elem, -sig_v_elem, 0.0])
                    total_stress = excavation_stress + elastic_stress
                    elem_stresses_unsupported[idx_e] = total_stress
                    
                    s_xx, s_yy, s_xy = total_stress[0], total_stress[1], total_stress[2]
                    center = (s_xx + s_yy) / 2.0
                    radius = np.sqrt(((s_xx - s_yy) / 2.0)**2 + s_xy**2)
                    sigma_n = center + radius * sin_phi
                    tau_m = radius
                    yield_func = tau_m - (c_rock * cos_phi - sigma_n * sin_phi)
                    if yield_func > 0:
                        yielded_unsupported[idx_e] = True
            
            K_total_stg1 = K_rock + K_support_active
            LU_total_stg1 = splu(csc_matrix(K_total_stg1[np.ix_(active_dofs_current, active_dofs_current)]))
            for step in range(5, 11):
                F_current = (step / 10) * F_ext_stages[stg_idx]
                u_current[active_dofs_current] = LU_total_stg1.solve(F_current[active_dofs_current])
        else:
            K_total_stg_k = K_rock + K_support_active
            LU_total_stg_k = splu(csc_matrix(K_total_stg_k[np.ix_(active_dofs_current, active_dofs_current)]))
            u_current[active_dofs_current] = LU_total_stg_k.solve(F_accumulated[active_dofs_current])
            
        u_stage_results[stg_idx] = u_current.copy()
        
        yielded_current = np.zeros(num_elements, dtype=bool)
        elem_stresses_current = np.zeros((num_elements, 3))
        for idx_e, elem in enumerate(elements):
            elem_coords = nodes[elem]
            y_elem = np.mean(elem_coords[:, 1])
            u_elem = u_current[np.array([2*elem[0], 2*elem[0]+1, 2*elem[1], 2*elem[1]+1,
                                        2*elem[2], 2*elem[2]+1, 2*elem[3], 2*elem[3]+1])]
            
            _, dN_dxi = shape_funcs(0.0, 0.0)
            J = dN_dxi @ elem_coords
            invJ = np.linalg.inv(J)
            dN_dx = invJ @ dN_dxi
            
            B = np.zeros((3, 8))
            for k in range(4):
                B[0, 2*k] = dN_dx[0, k]
                B[1, 2*k+1] = dN_dx[1, k]
                B[2, 2*k] = dN_dx[1, k]
                B[2, 2*k+1] = dN_dx[0, k]
                
            strain = B @ u_elem
            elastic_stress = D_e @ strain
            
            sig_v_elem = gamma_rock * (H_depth - y_elem)
            sig_h_elem = K0 * sig_v_elem
            excavation_stress = np.array([-sig_h_elem, -sig_v_elem, 0.0])
            total_stress = excavation_stress + elastic_stress
            elem_stresses_current[idx_e] = total_stress
            
            s_xx, s_yy, s_xy = total_stress[0], total_stress[1], total_stress[2]
            center = (s_xx + s_yy) / 2.0
            radius = np.sqrt(((s_xx - s_yy) / 2.0)**2 + s_xy**2)
            sigma_n = center + radius * sin_phi
            tau_m = radius
            yield_func = tau_m - (c_rock * cos_phi - sigma_n * sin_phi)
            if yield_func > 0:
                yielded_current[idx_e] = True
                
        yielded_stage_results[stg_idx] = yielded_current
        elem_stresses_stage_results[stg_idx] = elem_stresses_current
        
    u_final = u_current.copy()
    du_structural = u_final - u_install_state
    
    max_shotcrete_stress = 0.0
    if EA_comp > 0:
        for j in range(n_theta):
            n1 = node_dict[(0, j)]
            n2 = node_dict[(0, j+1)]
            p1_init, p2_init = nodes[n1], nodes[n2]
            p1_install = p1_init + u_install_state[np.array([2*n1, 2*n1+1])]
            p2_install = p2_init + u_install_state[np.array([2*n2, 2*n2+1])]
            p1_final = p1_init + u_final[np.array([2*n1, 2*n1+1])]
            p2_final = p2_init + u_final[np.array([2*n2, 2*n2+1])]
            L_install = np.linalg.norm(p2_install - p1_install)
            L_final = np.linalg.norm(p2_final - p1_final)
            strain_hoop = np.abs(L_final - L_install) / L_install
            if use_shotcrete:
                s_shot = E_shotcrete * strain_hoop
                if s_shot > max_shotcrete_stress:
                    max_shotcrete_stress = s_shot
                    
    max_bolt_force_kN = 0.0
    for b_elem in all_rockbolt_elements:
        n1, n2 = b_elem[0], b_elem[1]
        p1_init, p2_init = nodes[n1], nodes[n2]
        v1 = p1_init / np.linalg.norm(p1_init)
        v2 = p2_init / np.linalg.norm(p2_init)
        du1_radial = np.dot(du_structural[np.array([2*n1, 2*n1+1])], v1)
        du2_radial = np.dot(du_structural[np.array([2*n2, 2*n2+1])], v2)
        relative_u_radial = np.abs(du1_radial - du2_radial)
        p1_install = p1_init + u_install_state[np.array([2*n1, 2*n1+1])]
        p2_install = p2_init + u_install_state[np.array([2*n2, 2*n2+1])]
        L_install = np.linalg.norm(p2_install - p1_install)
        strain_bolt = relative_u_radial / L_install
        force_kn = E_bolt * A_bolt * strain_bolt * 1000.0
        if force_kn > max_bolt_force_kN:
            max_bolt_force_kN = force_kn
            
    crown_th_idx = np.argmin(np.abs(theta_vals - np.pi/2))
    crown_node = node_dict[(0, crown_th_idx)]
    crown_def_stage2 = np.sqrt(u_final[2*crown_node]**2 + u_final[2*crown_node+1]**2) * 1000.0
    
    last_stage_idx = stages_config[-1]["stage_idx"]
    yielded_percentage = (np.sum(yielded_stage_results[last_stage_idx]) / num_elements) * 100.0
    
    return {
        'crown_def': crown_def_stage2,
        'yielded_pct': yielded_percentage,
        'max_shotcrete_stress': max_shotcrete_stress,
        'max_bolt_force': max_bolt_force_kN
    }

# =============================================================================
# 4. RUN GENERALIZED PARAMETRIC SWEEPS
# =============================================================================
print("\n=== PARAMETRIC SENSITIVITY SWEEP STARTED (v37 Ultimate Edition) ===")

# Try to load sweep ranges dynamically from JSON
sweeps_config = params.get("batch_sweeps", {})

# 4.1 Cohesion Sweep (Unsupported vs. Supported)
if "cohesion_sweep" in sweeps_config:
    c_cfg = sweeps_config["cohesion_sweep"]
    cohesions = np.linspace(c_cfg.get("min_MPa", 0.2), c_cfg.get("max_MPa", 2.0), int(c_cfg.get("steps", 8)))
    print(f"--> Sweep 1/3: Solving Rock Mass Cohesion Sensitivity ({cohesions[0]:.2f} MPa - {cohesions[-1]:.2f} MPa, {len(cohesions)} steps)...")
else:
    print("--> Sweep 1/3: Solving Rock Mass Cohesion Sensitivity (0.2 MPa - 2.0 MPa)...")
    cohesions = np.array([0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.5, 2.0])
unsupported_defs = []
unsupported_yields = []
supported_defs = []
supported_yields = []

for c in cohesions:
    # Completely Unsupported
    res_unsub = run_parameterized_simulation(
        E_rock_init_val=5000.0, c_rock_init_val=c, phi_deg_val=30.0,
        use_shotcrete=False, t_shot=0.20, use_rockbolts=False, L_bolt_val=3.0, use_steel=False
    )
    unsupported_defs.append(res_unsub['crown_def'])
    unsupported_yields.append(res_unsub['yielded_pct'])
    
    # Supported (Shotcrete + Rockbolts + Steel Ribs)
    res_sub = run_parameterized_simulation(
        E_rock_init_val=5000.0, c_rock_init_val=c, phi_deg_val=30.0,
        use_shotcrete=True, t_shot=0.20, use_rockbolts=True, L_bolt_val=3.0, use_steel=True
    )
    supported_defs.append(res_sub['crown_def'])
    supported_yields.append(res_sub['yielded_pct'])

# 4.2 Shotcrete Thickness Sweep (Weak Ground: c_rock = 0.5 MPa)
if "shotcrete_sweep" in sweeps_config:
    sc_cfg = sweeps_config["shotcrete_sweep"]
    thicknesses_cm = np.linspace(sc_cfg.get("min_cm", 0.0), sc_cfg.get("max_cm", 35.0), int(sc_cfg.get("steps", 8)))
    print(f"--> Sweep 2/3: Solving Shotcrete Thickness Sensitivity ({thicknesses_cm[0]:.1f} cm - {thicknesses_cm[-1]:.1f} cm, {len(thicknesses_cm)} steps)...")
else:
    print("--> Sweep 2/3: Solving Shotcrete Thickness Sensitivity (0 cm - 35 cm)...")
    thicknesses_cm = np.array([0, 5, 10, 15, 20, 25, 30, 35])
shotcrete_defs = []
shotcrete_stresses = []

for t_cm in thicknesses_cm:
    t_m = t_cm / 100.0
    use_sc_flag = (t_cm > 0)
    res_sc = run_parameterized_simulation(
        E_rock_init_val=5000.0, c_rock_init_val=0.5, phi_deg_val=30.0,
        use_shotcrete=use_sc_flag, t_shot=t_m, use_rockbolts=False, L_bolt_val=3.0, use_steel=False
    )
    shotcrete_defs.append(res_sc['crown_def'])
    shotcrete_stresses.append(res_sc['max_shotcrete_stress'])

# 4.3 Rockbolt Length Sweep (Medium Ground: c_rock = 0.8 MPa)
if "rockbolt_sweep" in sweeps_config:
    rb_cfg = sweeps_config["rockbolt_sweep"]
    bolt_lengths = np.linspace(rb_cfg.get("min_m", 0.0), rb_cfg.get("max_m", 6.0), int(rb_cfg.get("steps", 7)))
    print(f"--> Sweep 3/3: Solving Rockbolt Length Sensitivity ({bolt_lengths[0]:.1f} m - {bolt_lengths[-1]:.1f} m, {len(bolt_lengths)} steps)...")
else:
    print("--> Sweep 3/3: Solving Rockbolt Length Sensitivity (0 m - 6 m)...")
    bolt_lengths = np.array([0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
bolt_defs = []
bolt_forces = []

for L_b in bolt_lengths:
    use_rb_flag = (L_b > 0)
    res_rb = run_parameterized_simulation(
        E_rock_init_val=5000.0, c_rock_init_val=0.8, phi_deg_val=30.0,
        use_shotcrete=False, t_shot=0.20, use_rockbolts=use_rb_flag, L_bolt_val=L_b, use_steel=False
    )
    bolt_defs.append(res_rb['crown_def'])
    bolt_forces.append(res_rb['max_bolt_force'])

# =============================================================================
# 5. PLOT SENSITIVITY SWEEP DASHBOARD (ENGLISH ACADEMIC LABELS)
# =============================================================================
fig, (ax_c, ax_sc, ax_rb) = plt.subplots(1, 3, figsize=(18, 6.2))
fig.suptitle("Automated Geotechnical & Support Sensitivity Analysis (Batch Run Dashboard)\n"
             "K0 = {K0_val:.3f} | Shape: {sh_val} | Preprocessor & Solver Core (v37)".format(
                 K0_val=K0, sh_val=params.get("preprocessing", {}).get("tunnel_type", "horseshoe").upper()
             ), fontsize=13, fontweight='bold', y=0.98)

# Panel A: Cohesion Sensitivity
color = 'tab:blue'
ax_c.set_xlabel('Rock Mass Cohesion, c [MPa]', fontweight='bold', fontsize=9.5)
ax_c.set_ylabel('Max Crown Displacement [mm]', color=color, fontweight='bold', fontsize=9.5)
line1 = ax_c.plot(cohesions, unsupported_defs, 'o--', color=color, lw=1.8, label='Displacement (Unsupported)')
line2 = ax_c.plot(cohesions, supported_defs, 'o-', color='darkblue', lw=2.2, label='Displacement (Supported)')
ax_c.tick_params(axis='y', labelcolor=color)
ax_c.grid(True, linestyle=':', alpha=0.6)

ax_c_right = ax_c.twinx()
color = 'tab:red'
ax_c_right.set_ylabel('Yielded Element Ratio (%)', color=color, fontweight='bold', fontsize=9.5)
line3 = ax_c_right.plot(cohesions, unsupported_yields, 's--', color='salmon', alpha=0.7, label='Yielded % (Unsupported)')
line4 = ax_c_right.plot(cohesions, supported_yields, 's-', color='crimson', lw=1.8, label='Yielded % (Supported)')
ax_c_right.tick_params(axis='y', labelcolor=color)

lines = line1 + line2 + line3 + line4
labels = [l.get_label() for l in lines]
ax_c.legend(lines, labels, loc='upper right', fontsize=8.5, framealpha=0.9)
ax_c.set_title('A. Impact of Rock Cohesion', fontsize=11, fontweight='bold', pad=10)

# Panel B: Shotcrete Thickness Sensitivity
color = 'tab:blue'
ax_sc.set_xlabel('Shotcrete Thickness [cm]', fontweight='bold', fontsize=9.5)
ax_sc.set_ylabel('Max Crown Displacement [mm]', color=color, fontweight='bold', fontsize=9.5)
line_sc1 = ax_sc.plot(thicknesses_cm, shotcrete_defs, 'o-', color=color, lw=2.2, label='Displacement')
ax_sc.tick_params(axis='y', labelcolor=color)
ax_sc.grid(True, linestyle=':', alpha=0.6)

ax_sc_right = ax_sc.twinx()
color = 'tab:orange'
ax_sc_right.set_ylabel('Max Shotcrete Compressive Stress [MPa]', color=color, fontweight='bold', fontsize=9.5)
line_sc2 = ax_sc_right.plot(thicknesses_cm[1:], shotcrete_stresses[1:], 's-', color=color, lw=2.0, label='Max Lining Stress')
ax_sc_right.axhline(fc_shotcrete_limit, color='red', linestyle='--', lw=1.5, label='Capacity Limit (16.7 MPa)')
ax_sc_right.tick_params(axis='y', labelcolor=color)

lines_sc = line_sc1 + line_sc2 + [plt.Line2D([0], [0], color='red', linestyle='--', lw=1.5, label='Capacity Limit')]
labels_sc = [l.get_label() for l in lines_sc]
ax_sc.legend(lines_sc, labels_sc, loc='upper right', fontsize=8.5, framealpha=0.9)
ax_sc.set_title('B. Impact of Shotcrete Thickness\n(Weak Ground, c = 0.5 MPa)', fontsize=11, fontweight='bold', pad=10)

# Panel C: Rockbolt Length Sensitivity
color = 'tab:blue'
ax_rb.set_xlabel('Rockbolt Length [m]', fontweight='bold', fontsize=9.5)
ax_rb.set_ylabel('Max Crown Displacement [mm]', color=color, fontweight='bold', fontsize=9.5)
line_rb1 = ax_rb.plot(bolt_lengths, bolt_defs, 'o-', color=color, lw=2.2, label='Displacement')
ax_rb.tick_params(axis='y', labelcolor=color)
ax_rb.grid(True, linestyle=':', alpha=0.6)

ax_rb_right = ax_rb.twinx()
color = 'tab:green'
ax_rb_right.set_ylabel('Max Bolt Tensile Force [kN]', color=color, fontweight='bold', fontsize=9.5)
line_rb2 = ax_rb_right.plot(bolt_lengths[1:], bolt_forces[1:], 's-', color=color, lw=2.0, label='Max Bolt Force')
ax_rb_right.axhline(T_bolt_limit, color='red', linestyle='--', lw=1.5, label='Capacity Limit (200.0 kN)')
ax_rb_right.tick_params(axis='y', labelcolor=color)

lines_rb = line_rb1 + line_rb2 + [plt.Line2D([0], [0], color='red', linestyle='--', lw=1.5, label='Capacity Limit')]
labels_rb = [l.get_label() for l in lines_rb]
ax_rb.legend(lines_rb, labels_rb, loc='upper right', fontsize=8.5, framealpha=0.9)
ax_rb.set_title('C. Impact of Rockbolt Length\n(Zemin c = 0.8 MPa)', fontsize=11, fontweight='bold', pad=10)

plt.tight_layout()

# Save logic
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
summary_data = {
    "timestamp": timestamp,
    "cohesion_sweep": {
        "cohesions_MPa": cohesions.tolist(),
        "unsupported_defs_mm": [float(x) for x in unsupported_defs],
        "unsupported_yields_pct": [float(x) for x in unsupported_yields],
        "supported_defs_mm": [float(x) for x in supported_defs],
        "supported_yields_pct": [float(x) for x in supported_yields]
    },
    "shotcrete_sweep": {
        "thicknesses_cm": thicknesses_cm.tolist(),
        "defs_mm": [float(x) for x in shotcrete_defs],
        "stresses_MPa": [float(x) for x in shotcrete_stresses]
    },
    "rockbolt_sweep": {
        "lengths_m": bolt_lengths.tolist(),
        "defs_mm": [float(x) for x in bolt_defs],
        "forces_kN": [float(x) for x in bolt_forces]
    }
}

if is_cloud:
    fig_path = f"/workspace/scratch/tunnel_sensitivity_sweep_v37.png"
    fig.savefig(fig_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    # Sync with output files
    shutil.copy(fig_path, "/workspace/out/tunnel_sensitivity_sweep_v37.png")
    
    json_path = "/workspace/out/tunnel_sensitivity_summary_v37.json"
    with open(json_path, 'w', encoding='utf-8') as fj:
        json.dump(summary_data, fj, indent=4, ensure_ascii=False)
    print("--> [Synced] tunnel_sensitivity_sweep_v37.png published successfully.")
else:
    script_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in globals() else os.getcwd()
    img_name = f"tunnel_sensitivity_sweep_{timestamp}.png"
    img_path = os.path.join(script_dir, img_name)
    fig.savefig(img_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    json_name = f"tunnel_sensitivity_summary_{timestamp}.json"
    json_path = os.path.join(script_dir, json_name)
    with open(json_path, 'w', encoding='utf-8') as fj:
        json.dump(summary_data, fj, indent=4, ensure_ascii=False)
    print(f"--> [Local Save] Saved sensitivity plot to: {img_path}")
